
rtl/lib.sv
rtl/alignment_units.sv
rtl/alu_control.sv
rtl/mul_unit.sv
rtl/div_unit.sv
rtl/branch_controller.sv
rtl/csr_file.sv
rtl/imm_gen.sv
rtl/decode_control.sv
rtl/reg_file.sv
rtl/forwarding_unit.sv
rtl/hazard_controller.sv
rtl/pipeline_controller.sv
rtl/decompressor.sv
rtl/iadu.sv
rtl/mem_controller.sv
rtl/lsu.sv
rtl/exception_encoder.sv
rtl/crypto/crypto_bitmanip_lib.sv
rtl/crypto/aes_unit.sv
rtl/crypto/crypto_unit.sv
rtl/pqc/adder_16x16.v
rtl/pqc/sub_32x32.v
rtl/pqc/multiplier_16x16.v
rtl/pqc/montgomery.sv
rtl/pqc/pqc_top.sv
rtl/alu.sv
rtl/data_path.sv
rtl/control_unit.sv
rtl/core_dbg_fsm.sv
rtl/rv32imc.sv
rtl/rv32imc_top.sv